repos:
  - repo: local
    hooks:
      - id: pre-commit
        name: Pre-Commit Check
        entry: uv run python -X utf8 pre-commit.py
        language: system
        pass_filenames: false
        always_run: true
