services:
  jdownloader:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    environment:
      - TZ=Europe/Berlin
      - CONFIG_VOLUMES=/config/volumes
    ports:
      - "9090:5800"
      - "3129:3129"
    volumes:
      - ${CONFIG_VOLUMES}/jdownloader:/config
      - ${CONFIG_VOLUMES}/downloads:/downloads
    logging:
      options:
        max-size: "10m"
        max-file: "1"
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8989:8191"
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Berlin
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=600
    restart: unless-stopped


  # Only enable these if you can't use the cli_tester.py or want to expand a feature that needs the real services:
  #  radarr:
  #    image: lscr.io/linuxserver/radarr:latest
  #    container_name: radarr
  #    environment:
  #      - PGID=1000
  #      - PUID=1000
  #      - TZ=Europe/Berlin
  #      - CONFIG_VOLUMES=/config/volumes
  #    ports:
  #      - "9091:7878"
  #    volumes:
  #      - ${CONFIG_VOLUMES}/radarr/config:/config
  #      - ${CONFIG_VOLUMES}/radarr/movies:/movies
  #      - ${CONFIG_VOLUMES}/downloads:/downloads
  #    logging:
  #      options:
  #        max-size: "10m"
  #        max-file: "1"
  #    restart: unless-stopped
  #
  #  sonarr:
  #    image: lscr.io/linuxserver/sonarr:latest
  #    container_name: sonarr
  #    environment:
  #      - PGID=1000
  #      - PUID=1000
  #      - TZ=Europe/Berlin
  #      - CONFIG_VOLUMES=/config/volumes
  #    ports:
  #      - "9092:8989"
  #    volumes:
  #      - ${CONFIG_VOLUMES}/sonarr/config:/config
  #      - ${CONFIG_VOLUMES}/sonarr/tv:/tv
  #      - ${CONFIG_VOLUMES}/downloads:/downloads
  #    logging:
  #      options:
  #        max-size: "10m"
  #        max-file: "1"
  #    restart: unless-stopped
  #
  #  lazylibrarian:
  #    image: lscr.io/linuxserver/lazylibrarian:latest
  #    container_name: lazylibrarian
  #    environment:
  #      - PGID=1000
  #      - PUID=1000
  #      - TZ=Europe/Berlin
  #      - CONFIG_VOLUMES=/config/volumes
  #    ports:
  #      - "9093:5299"
  #    volumes:
  #      - ${CONFIG_VOLUMES}/lazylibrarian/config:/config
  #      - ${CONFIG_VOLUMES}/lazylibrarian/documents:/documents
  #      - ${CONFIG_VOLUMES}/downloads:/downloads
  #    logging:
  #      options:
  #        max-size: "10m"
  #        max-file: "1"
  #    restart: unless-stopped
