services:
  quasarr:
    container_name: 'Quasarr'
    image: 'ghcr.io/rix1337/quasarr:latest'
    ports:
      - '8080:8080'
    volumes:
      - '/path/to/config/:/config:rw'
    environment:
      - 'INTERNAL_ADDRESS=http://192.168.1.1:8080'
      - 'EXTERNAL_ADDRESS=https://foo.bar/'
      - 'DISCORD=https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN'
      - 'USER=admin'
      - 'PASS=change-me'
      - 'AUTH=form'
      - 'SILENT=True'
      - 'TZ=Europe/Berlin'
