services:
    quasarr:
        container_name: 'Quasarr'
        ports:
            - '8080:8080'
        volumes:
            - '/path/to/config/:/config:rw'
        environment:
            - 'INTERNAL_ADDRESS=http://192.168.1.1:8080'
            - 'EXTERNAL_ADDRESS=https://foo.bar/'
            - 'DISCORD=https://discord.com/api/webhooks/1234567890/ABCDEFGHIJKLMN'
            - 'EXTERNAL_ADDRESS=https://quasarr-host.name/ini?token=123...'
            - 'SILENT=True'
            - 'DEBUG='
        image: 'ghcr.io/rix1337/quasarr:latest'
